#!/usr/bin/env -S ruby -w

require 'lobstersbot'

class Bot < Summer::Connection
  include Lobstersbot::PluggableConnection

  include Lobstersbot::Tell
  include Lobstersbot::Rss
  include Lobstersbot::Salute
  include Lobstersbot::Title
end

Bot.new("irc.freenode.net")
